/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "surface-tint": "#0053db",
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary-container": "#ffede6",
        "error": "#ba1a1a",
        "on-surface": "#191b23",
        "on-primary": "#ffffff",
        "surface-container-high": "#e7e7f3",
        "on-secondary-container": "#1d3989",
        "on-primary-fixed-variant": "#003ea8",
        "surface-variant": "#e1e2ed",
        "inverse-surface": "#2e3039",
        "surface-container-low": "#f3f3fe",
        "secondary-container": "#8fa7fe",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#00164e",
        "tertiary-fixed": "#ffdbcd",
        "surface-dim": "#d9d9e5",
        "surface-bright": "#faf8ff",
        "surface-container-highest": "#e1e2ed",
        "on-secondary-fixed-variant": "#264191",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f0f0fb",
        "on-surface-variant": "#434655",
        "primary-container": "#2563eb",
        "outline-variant": "#c3c6d7",
        "surface": "#faf8ff",
        "surface-container": "#ededf9",
        "on-tertiary-fixed": "#360f00",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#00174b",
        "background": "#faf8ff",
        "primary-fixed": "#dbe1ff",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#bc4800",
        "secondary-fixed-dim": "#b6c4ff",
        "on-background": "#191b23",
        "tertiary": "#943700",
        "inverse-primary": "#b4c5ff",
        "primary": "#004ac6",
        "tertiary-fixed-dim": "#ffb596",
        "secondary": "#4059aa",
        "outline": "#737686",
        "on-tertiary-fixed-variant": "#7d2d00",
        "secondary-fixed": "#dce1ff",
        "on-primary-container": "#eeefff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "sidebar-width": "280px",
        "2xl": "48px",
        "container-max": "1440px",
        xs: "4px",
        unit: "4px",
        sm: "8px",
        xl: "32px",
        lg: "24px",
        "3xl": "64px",
        md: "16px",
      },
      fontFamily: {
        "label-md": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        code: ["Geist", "monospace"],
        "label-sm": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        code: ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1440px",
      },
      width: {
        "sidebar-width": "280px",
      },
    },
  },
  plugins: [],
};
